# Generated by Django 5.1 on 2024-08-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product')),
                ('description', models.TextField(max_length=1000, null=True)),
                ('origin', models.CharField(default='', max_length=100)),
                ('trademark', models.CharField(default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
